### ISSUE TITLE
deleteConflictingFiles

### ISSUE THREAD

**Issue by peter-budo** [techatspree/android-archetypes#24]
I'm still sort of newbie in Maven so may request/comment can be silly, but here we go. It is my understanding that android.maven.plugin project with release of 3.0.0-alpha-3 in issue 182 deprecated deleteConflictingFiles parameter. However this still exists in pom when generated with your archetypes. Can you please remove <deleteConflictingFiles>true</deleteConflictingFiles>?

**Comment by cescoffier** [comment]
Thanks, will do !

**Comment by peter-budo** [comment]
Also, when I can keep bugging android-maven-plugin 3.1.0 was released yesterday ;)

**Comment by mosabua** [comment]
You can just implement the proposed changes yourself and send a pull request..

**Comment by peter-budo** [comment]
I guess I will need some help on that. I got clone from git, able to build and test android-quickstart. However android-with-test wouldn't pass. Bellow you can see maven final report. Would it be possible to get some quick notes in regards of configuration (I think I'm missing something)

[DEBUG] ANDROID-040-000: Executed command: Commandline = /bin/sh -c /Users/Peter/android-sdk-macosx/platform-tools/aapt dump xmltree /Users/Peter/github/android-archetypes/android-with-test/target/it/projects/default/sample-with-test/sample-with-test/target/sample-with-test-1.0-SNAPSHOT.apk AndroidManifest.xml, Result = 0
[INFO] Found 0 devices connected with the Android Debug Bridge
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] sample-with-test - Parent ......................... SUCCESS [0.002s]
[INFO] sample-with-test - Application .................... SUCCESS [1:12.342s]
[INFO] sample-with-test-it - Integration tests ........... FAILURE [3.479s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:05.056s
[INFO] Finished at: Fri Feb 03 13:49:55 GMT 2012
[INFO] Final Memory: 13M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.0.0:internal-pre-integration-test (default-internal-pre-integration-test) on project sample-with-test-it-it: No online devices attached. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.0.0:internal-pre-integration-test (default-internal-pre-integration-test) on project sample-with-test-it-it: No online devices attached.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: No online devices attached.
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.doWithDevices(AbstractAndroidMojo.java:624)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.undeployApk(AbstractAndroidMojo.java:657)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.undeployApk(AbstractAndroidMojo.java:641)
    at com.jayway.maven.plugins.android.AbstractAndroidMojo.deployDependencies(AbstractAndroidMojo.java:559)
    at com.jayway.maven.plugins.android.phase11preintegrationtest.InternalPreIntegrationTestMojo.execute(InternalPreIntegrationTestMojo.java:36)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
    ... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :sample-with-test-it-it

**Comment by mosabua** [comment]
The error message says it right there. No device attached...

Connected a device or emulator and start adb. check the device is online with adb devices

**Comment by peter-budo** [comment]
Damn I forgot it. Hiding in the corner with shame...
